services:
  database:
    image: mariadb:latest
    container_name: crm_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crm_db
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mariadb", "-uroot", "-proot", "-e", "SELECT 1"]
      interval: 5s
      retries: 5
      start_period: 10s


  backend:
    build: ./backend
    container_name: crm_backend
    restart: always
    depends_on:
      database:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/crm_db
      SPRING_DATASOURCE_USERNAME: crm_admin
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: crm_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

volumes:
  mariadb_data:
